-- Backfill user columns expected by the current ORM and auth flow.
-- Safe to run multiple times on PostgreSQL.

ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS daily_ai_limit INTEGER;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS daily_sync_limit INTEGER;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS quota_reset_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS trial_active BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS trial_expires_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS total_ai_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS total_api_calls INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS total_scheduling_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;