"""added preferences column to user

Revision ID: 06b375a1aa6e
Revises: 8c80dd15128e
Create Date: 2026-04-09 23:58:21.990171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06b375a1aa6e"
down_revision: Union[str, None] = "8c80dd15128e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_webhooks")
    op.drop_index("ix_user_profiles_user_id", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index("ix_session_token", table_name="session")
    op.drop_index("ix_session_user_id", table_name="session")
    op.drop_table("session")
    op.drop_table("schema_migrations")
    op.drop_index("ix_account_userId", table_name="account")
    op.drop_table("account")
    op.alter_column(
        "bookings",
        "booking_code",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "bookings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "bookings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index("ix_bookings_status", table_name="bookings")
    op.drop_index("ix_bookings_status_user", table_name="bookings")
    op.drop_index("ix_bookings_user_start_end", table_name="bookings")
    op.create_index(
        "ix_bookings_booking_code", "bookings", ["booking_code"], unique=False
    )
    op.create_index(
        "ix_bookings_user_start_time",
        "bookings",
        ["user_id", "start_time"],
        unique=False,
    )
    op.alter_column(
        "event_types", "is_public", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "event_types",
        "payment_currency",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'USD'::text"),
    )
    op.alter_column(
        "event_types",
        "team_assignment_method",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'round_robin'::text"),
    )
    op.alter_column(
        "event_types",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "event_types",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index("uq_event_types_user_id_slug", table_name="event_types")
    op.create_index(
        "ix_event_types_user_slug", "event_types", ["user_id", "slug"], unique=False
    )
    op.alter_column(
        "events",
        "event_type_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "location",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.execute("UPDATE events SET is_meeting = FALSE WHERE is_meeting IS NULL")
    op.alter_column("events", "is_meeting", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "events",
        "meeting_provider",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.execute("UPDATE events SET is_reminded = FALSE WHERE is_reminded IS NULL")
    op.alter_column("events", "is_reminded", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index("ix_events_source", table_name="events")
    op.drop_index("ix_events_user_start_end", table_name="events")
    op.create_index(
        op.f("ix_events_event_type_id"), "events", ["event_type_id"], unique=False
    )
    op.create_foreign_key(
        None, "events", "event_types", ["event_type_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "notifications",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications", "type", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "notifications",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
    )
    op.drop_index("idx_notifications_is_read", table_name="notifications")
    op.drop_index("ix_notifications_id", table_name="notifications")
    op.drop_index("ix_notifications_is_read", table_name="notifications")
    op.drop_index("ix_notifications_type", table_name="notifications")
    op.drop_column("notifications", "recipient")
    op.drop_column("notifications", "updated_at")
    op.alter_column(
        "user_tokens", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS preferences JSON")
    op.alter_column(
        "users",
        "username",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'UTC'::character varying"),
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "email_verification_code",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "subscription_status",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'inactive'::character varying"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index("idx_users_deleted_at", table_name="users")
    op.drop_index("idx_users_razorpay_customer_id", table_name="users")
    op.drop_index("idx_users_razorpay_subscription_id", table_name="users")
    op.drop_index("idx_users_stripe_customer_id", table_name="users")
    op.drop_index("idx_users_tenant_id", table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "role")
    op.drop_column("users", "name")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "mfa_secret")
    op.drop_column("users", "image")
    op.drop_column("users", "location")
    op.drop_column("users", "mfa_enabled")
    op.drop_column("users", "consent_analytics")
    op.drop_column("users", "tenant_id")
    op.drop_column("users", "last_quota_warning_at")
    op.drop_column("users", "ai_quota_warning_sent")
    op.drop_column("users", "sync_quota_warning_sent")
    op.drop_column("users", "consent_notifications")
    op.drop_column("users", "consent_ai_training")
    op.drop_column("users", "last_usage_reset")
    op.drop_column("users", "bio")
    op.drop_column("users", "is_active")
    op.drop_column("users", "job_title")
    op.alter_column(
        "webhook_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "webhook_subscriptions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "webhook_subscriptions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "webhook_subscriptions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "webhook_subscriptions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "webhook_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "job_title", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("bio", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "last_usage_reset",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "consent_ai_training",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "consent_notifications",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "sync_quota_warning_sent",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "ai_quota_warning_sent",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_quota_warning_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("tenant_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "consent_analytics",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "mfa_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "location", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("image", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "mfa_secret", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.VARCHAR(length=20),
            server_default=sa.text("'member'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "stripe_customer_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_superuser",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("idx_users_tenant_id", "users", ["tenant_id"], unique=False)
    op.create_index(
        "idx_users_stripe_customer_id", "users", ["stripe_customer_id"], unique=False
    )
    op.create_index(
        "idx_users_razorpay_subscription_id",
        "users",
        ["razorpay_subscription_id"],
        unique=False,
    )
    op.create_index(
        "idx_users_razorpay_customer_id",
        "users",
        ["razorpay_customer_id"],
        unique=False,
    )
    op.create_index("idx_users_deleted_at", "users", ["deleted_at"], unique=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "users",
        "subscription_status",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'inactive'::character varying"),
    )
    op.alter_column(
        "users",
        "email_verification_code",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'UTC'::character varying"),
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("users", "preferences")
    op.alter_column(
        "user_tokens", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.add_column(
        "notifications",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "recipient",
            sa.VARCHAR(length=255),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index("ix_notifications_type", "notifications", ["type"], unique=False)
    op.create_index(
        "ix_notifications_is_read", "notifications", ["is_read"], unique=False
    )
    op.create_index("ix_notifications_id", "notifications", ["id"], unique=False)
    op.create_index(
        "idx_notifications_is_read", "notifications", ["is_read"], unique=False
    )
    op.alter_column(
        "notifications",
        "data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "notifications", "type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "notifications",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_index(op.f("ix_events_event_type_id"), table_name="events")
    op.create_index(
        "ix_events_user_start_end",
        "events",
        ["user_id", "start_time", "end_time"],
        unique=False,
    )
    op.create_index("ix_events_source", "events", ["source"], unique=False)
    op.alter_column(
        "events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column("events", "is_reminded", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "events",
        "meeting_provider",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column("events", "is_meeting", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "events",
        "location",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "event_type_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index("ix_event_types_user_slug", table_name="event_types")
    op.create_index(
        "uq_event_types_user_id_slug", "event_types", ["user_id", "slug"], unique=True
    )
    op.alter_column(
        "event_types",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "event_types",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "event_types",
        "team_assignment_method",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'round_robin'::text"),
    )
    op.alter_column(
        "event_types",
        "payment_currency",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'USD'::text"),
    )
    op.alter_column(
        "event_types", "is_public", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_index("ix_bookings_user_start_time", table_name="bookings")
    op.drop_index("ix_bookings_booking_code", table_name="bookings")
    op.create_index(
        "ix_bookings_user_start_end",
        "bookings",
        ["user_id", "start_time", "end_time"],
        unique=False,
    )
    op.create_index(
        "ix_bookings_status_user", "bookings", ["status", "user_id"], unique=False
    )
    op.create_index("ix_bookings_status", "bookings", ["status"], unique=False)
    op.alter_column(
        "bookings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "bookings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "bookings",
        "booking_code",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_table(
        "account",
        sa.Column("id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "userId", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "accountId", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "providerId", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("accessToken", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("refreshToken", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("idToken", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "accessTokenExpiresAt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "refreshTokenExpiresAt",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["users.id"], name="account_userId_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="account_pkey"),
    )
    op.create_index("ix_account_userId", "account", ["userId"], unique=False)
    op.create_table(
        "schema_migrations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "migration_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "applied_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="schema_migrations_pkey"),
        sa.UniqueConstraint(
            "migration_name", name="schema_migrations_migration_name_key"
        ),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "user_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ip_address", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="session_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="session_pkey"),
    )
    op.create_index("ix_session_user_id", "session", ["user_id"], unique=False)
    op.create_index("ix_session_token", "session", ["token"], unique=True)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "subscription_tier",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "monthly_ai_credits", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("used_ai_credits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "onboarding_complete", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "preferred_locale",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avatar_url", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_profiles_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="user_profiles_pkey"),
    )
    op.create_index(
        "ix_user_profiles_user_id", "user_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "processed_webhooks",
        sa.Column(
            "event_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "provider", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "processed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("event_id", name="processed_webhooks_pkey"),
    )
    # ### end Alembic commands ###
