"""Enhance audit logging for SaaS

Revision ID: 5bf775d35f35
Revises: ac0a38e31855
Create Date: 2026-04-25 13:09:49.895150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf775d35f35'
down_revision: Union[str, None] = 'ac0a38e31855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='success'))
        batch_op.alter_column('user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_team_id'), ['team_id'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey') # SQLite nameless constraint fix
        batch_op.create_foreign_key('fk_audit_logs_team_id', 'teams', ['team_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_team_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_team_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
