"""webhook_logs_table

Revision ID: 8c80dd15128e
Revises: 451d24f3b91c
Create Date: 2026-04-09 16:50:08.024075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c80dd15128e"
down_revision: Union[str, None] = "451d24f3b91c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS webhook_logs CASCADE")
    op.execute("DROP TABLE IF EXISTS webhook_subscriptions CASCADE")

    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("secret", sa.String(), nullable=False),
        sa.Column("external_subscription_id", sa.String(), nullable=True),
        sa.Column("client_state", sa.String(), nullable=True),
        sa.Column("last_triggered", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_subscriptions_user_id"),
        "webhook_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_subscriptions_external_subscription_id"),
        "webhook_subscriptions",
        ["external_subscription_id"],
        unique=False,
    )

    op.create_table(
        "webhook_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("webhook_id", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("request_status", sa.Integer(), nullable=False),
        sa.Column("request_error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["webhook_id"], ["webhook_subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_logs_webhook_id"), "webhook_logs", ["webhook_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_logs_webhook_id"), table_name="webhook_logs")
    op.drop_table("webhook_logs")
    op.drop_index(
        op.f("ix_webhook_subscriptions_external_subscription_id"),
        table_name="webhook_subscriptions",
    )
    op.drop_index(
        op.f("ix_webhook_subscriptions_user_id"), table_name="webhook_subscriptions"
    )
    op.drop_table("webhook_subscriptions")
    # ### end Alembic commands ###
