"""SaaS Grade: Definitive Multi-Tenant Expansion

Revision ID: a68c60ebf326
Revises: 
Create Date: 2026-03-29 01:54:36.896159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68c60ebf326'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_organizations',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_org_id'), 'workspaces', ['org_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.drop_table('playing_with_neon')
    op.add_column('account', sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('account', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('account', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('account_user_id_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_column('account', 'refresh_token_expires_at')
    op.drop_column('account', 'accessTokenExpiresAt')
    op.drop_column('account', 'access_token_expires_at')
    op.drop_column('account', 'user_id')
    op.drop_column('account', 'createdAt')
    op.drop_column('account', 'scope')
    op.drop_column('account', 'access_token')
    op.drop_column('account', 'refreshTokenExpiresAt')
    op.drop_column('account', 'updated_at')
    op.drop_column('account', 'refresh_token')
    op.drop_column('account', 'updatedAt')
    op.drop_column('account', 'provider_id')
    op.drop_column('account', 'account_id')
    op.drop_column('account', 'created_at')
    op.drop_column('account', 'id_token')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('auth_sessions', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('events', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('events', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('events', 'is_busy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_events_category'), table_name='events')
    op.drop_index(op.f('idx_events_start_time'), table_name='events')
    op.drop_index(op.f('idx_events_user_id'), table_name='events')
    op.drop_index(op.f('idx_events_user_time'), table_name='events')
    op.create_index(op.f('ix_events_org_id'), 'events', ['org_id'], unique=False)
    op.create_index(op.f('ix_events_provider_id'), 'events', ['provider_id'], unique=False)
    op.create_index(op.f('ix_events_provider_source'), 'events', ['provider_source'], unique=False)
    op.create_index('ix_events_user_availability', 'events', ['user_id', 'start_time', 'end_time'], unique=False, postgresql_where='is_busy = true')
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'events', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_status'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('organizations', sa.Column('slug', sa.String(length=100), nullable=False))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint(op.f('organizations_owner_id_fkey'), 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'owner_id')
    op.alter_column('preferences', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('session', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('session', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('session_user_id_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_column('session', 'ip_address')
    op.drop_column('session', 'createdAt')
    op.drop_column('session', 'expires_at')
    op.drop_column('session', 'created_at')
    op.drop_column('session', 'updated_at')
    op.drop_column('session', 'updatedAt')
    op.drop_column('session', 'user_id')
    op.drop_column('session', 'user_agent')
    op.add_column('todos', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('todos', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('todos', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('todos', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_index(op.f('idx_todos_user_id'), table_name='todos')
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_org_id'), 'todos', ['org_id'], unique=False)
    op.create_foreign_key(None, 'todos', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'todos', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # Pre-populate existing NULL values before enforcing NOT NULL
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE users SET is_superuser = false WHERE is_superuser IS NULL")
    op.execute("UPDATE users SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE users SET updated_at = now() WHERE updated_at IS NULL")

    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_onesignal_id'), table_name='users')
    op.drop_index(op.f('ix_users_timezone'), table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'onesignal_id')
    op.drop_column('users', 'emailVerified')
    op.drop_column('users', 'createdAt')
    op.alter_column('verification', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('verification', 'createdAt')
    op.drop_column('verification', 'expires_at')
    op.drop_column('verification', 'updated_at')
    op.drop_column('verification', 'updatedAt')
    op.drop_column('verification', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('verification', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('verification', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('verification', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('verification', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('verification', 'id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('users', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('emailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('onesignal_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index(op.f('ix_users_timezone'), 'users', ['timezone'], unique=False)
    op.create_index(op.f('ix_users_onesignal_id'), 'users', ['onesignal_id'], unique=False)
    op.create_index(op.f('idx_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.create_index(op.f('idx_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.alter_column('todos', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('todos', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_todos_org_id'), table_name='todos')
    op.drop_column('todos', 'workspace_id')
    op.drop_column('todos', 'org_id')
    op.add_column('session', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_user_id_fkey'), 'session', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('session', 'userId',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('session', 'id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('preferences', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('organizations', sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('organizations_owner_id_fkey'), 'organizations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'slug')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_status'), 'notifications', ['status'], unique=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_index('ix_events_user_availability', table_name='events', postgresql_where='is_busy = true')
    op.drop_index(op.f('ix_events_provider_source'), table_name='events')
    op.drop_index(op.f('ix_events_provider_id'), table_name='events')
    op.drop_index(op.f('ix_events_org_id'), table_name='events')
    op.create_index(op.f('idx_events_user_time'), 'events', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index(op.f('idx_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('idx_events_category'), 'events', ['category'], unique=False)
    op.alter_column('events', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'is_busy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('events', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('events', 'workspace_id')
    op.drop_column('events', 'org_id')
    op.alter_column('bookings', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auth_sessions', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('account', sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('account_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('provider_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('refreshTokenExpiresAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('access_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('accessTokenExpiresAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('refresh_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_user_id_fkey'), 'account', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('account', 'userId',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('account', 'id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('account', 'expiresAt')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_org_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('user_organizations')
    # ### end Alembic commands ###
