"""Add usage tracking columns

Revision ID: ac0a38e31855
Revises: dccb1cf21fdd
Create Date: 2026-04-25 13:02:28.639557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0a38e31855'
down_revision: Union[str, None] = 'dccb1cf21fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ai_tokens', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('total_api_calls', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('total_scheduling_count', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_scheduling_count')
        batch_op.drop_column('total_api_calls')
        batch_op.drop_column('total_ai_tokens')

    # ### end Alembic commands ###
