"""Align schema with models and add missing indexes v2

Revision ID: dccb1cf21fdd
Revises: 59fa74f48ce2
Create Date: 2026-04-24 01:09:24.476727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccb1cf21fdd'
down_revision: Union[str, None] = '59fa74f48ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_bookings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_bookings_assigned_to_users', 'users', ['assigned_to'], ['id'])

    try:
        with op.batch_alter_table('teams', schema=None) as batch_op:
            batch_op.drop_column('is_deleted')
            batch_op.drop_column('deleted_at')
    except Exception as e:
        print(f"Skipping migration on non-existent column: {e}")

    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('is_superuser',
                existing_type=sa.INTEGER(),
                type_=sa.Boolean(),
                existing_nullable=False,
                existing_server_default=sa.text('0'))
            batch_op.alter_column('onboarding_completed',
                existing_type=sa.INTEGER(),
                type_=sa.Boolean(),
                existing_nullable=False,
                existing_server_default=sa.text('0'))
            batch_op.drop_index('ix_users_stripe_customer_id')
            batch_op.drop_index('ix_users_stripe_subscription_id')
            batch_op.drop_column('is_deleted')
            batch_op.drop_column('deleted_at')
    except Exception as e:
        print(f"Skipping migration on non-existent column: {e}")

    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_webhook_logs_event_id'), ['event_id'], unique=True)

    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_workflows_deleted_at'))

    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_deleted_at'))

    with op.batch_alter_table('webhook_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_logs_event_id'))
        batch_op.drop_column('event_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index('ix_users_stripe_subscription_id', ['stripe_subscription_id'], unique=False)
        batch_op.create_index('ix_users_stripe_customer_id', ['stripe_customer_id'], unique=False)
        batch_op.alter_column('onboarding_completed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_superuser',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('team_bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_bookings_assigned_to_users', type_='foreignkey')

    # ### end Alembic commands ###
