"""Add MFA and audit log tables

Revision ID: f1a2b3c4d5e6
Revises: 06b375a1aa6e
Create Date: 2024-12-01 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, None] = "06b375a1aa6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Create user_mfa table
    if not inspector.has_table("user_mfa"):
        op.create_table(
            "user_mfa",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("mfa_type", sa.String(), nullable=False),
            sa.Column("secret", sa.String(), nullable=True),
            sa.Column("backup_codes", postgresql.JSON(), nullable=True),
            sa.Column(
                "is_enabled", sa.Boolean(), nullable=False, server_default="false"
            ),
            sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        )
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_mfa_user_id ON user_mfa (user_id)")

    # Create audit_logs table
    if not inspector.has_table("audit_logs"):
        op.create_table(
            "audit_logs",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column(
                "timestamp",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            ),
            sa.Column("event_type", sa.String(length=50), nullable=False),
            sa.Column("event_category", sa.String(length=30), nullable=False),
            sa.Column(
                "severity", sa.String(length=10), nullable=False, server_default="info"
            ),
            sa.Column("user_id", sa.String(), nullable=True),
            sa.Column("user_email", sa.String(length=255), nullable=True),
            sa.Column("ip_address", sa.String(length=45), nullable=True),
            sa.Column("user_agent", sa.Text(), nullable=True),
            sa.Column("action", sa.String(length=50), nullable=False),
            sa.Column("resource_type", sa.String(length=50), nullable=False),
            sa.Column("resource_id", sa.String(length=100), nullable=True),
            sa.Column(
                "result", sa.String(length=10), nullable=False, server_default="success"
            ),
            sa.Column("failure_reason", sa.Text(), nullable=True),
            sa.Column("metadata", postgresql.JSON(), nullable=True),
            sa.Column(
                "compliance_standards",
                sa.JSON(),
                server_default=sa.text("'[\"SOC2\"]'"),
            ),
            sa.Column("data_subjects_affected", sa.Integer(), nullable=True),
            sa.Column("data_categories", postgresql.JSON(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON audit_logs (user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_event_type ON audit_logs (event_type)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_timestamp ON audit_logs (timestamp)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_audit_logs_ip_address ON audit_logs (ip_address)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_logs_ip_address", table_name="audit_logs")
    op.drop_index("ix_audit_logs_timestamp", table_name="audit_logs")
    op.drop_index("ix_audit_logs_event_type", table_name="audit_logs")
    op.drop_index("ix_audit_logs_user_id", table_name="audit_logs")
    op.drop_table("audit_logs")

    op.drop_index("ix_user_mfa_user_id", table_name="user_mfa")
    op.drop_table("user_mfa")
    # ### end Alembic commands ###
