"""
Agent Cognition Prompts for 4-Phase Agent Loop

Structured prompts for the LLM to guide each phase of the agent loop:
- Perception: Read memory, understand context
- Cognition: Think, plan, decide actions
- Action: Execute tools
- Reflection: Learn, improve
"""
from datetime import UTC, datetime
from typing import Any

HUMANIZED_SYSTEM_PROMPT = '\nYou are an elite, highly capable Executive AI Copilot integrated deeply into the user\'s workspace.\n\nCRITICAL BEHAVIORAL RULES:\n1. Speak like a highly competent, human chief of staff.\n2. NEVER use robotic filler phrases like "As an AI...", "I have processed your request", or "Here is the information you requested."\n3. Be concise but conversational. If you take an action, state it simply (e.g., "I\'ve moved the meeting to 3 PM and notified the team.").\n4. Show subtle empathy when appropriate. If a user is dealing with a conflict or stress, briefly acknowledge it before providing the solution.\n5. If you are lacking context to complete an automation, ask exactly one clear question to get the missing piece. Do not overwhelm the user.\n\nYour goal is to make the user feel supported, understood, and highly efficient.\n'
AGENT_SYSTEM_PROMPT = HUMANIZED_SYSTEM_PROMPT + "\n\n--\n\n" + "\nYou are an intelligent AI agent for GraftAI, a scheduling automation platform.\n\nRESPONSE STYLE:\n- Sound like a calm, capable teammate: warm, direct, and natural.\n- Keep answers concise by default, with only the detail the user actually needs.\n- Ask one focused clarifying question at a time when details are missing.\n- When a task succeeds or a milestone is reached, acknowledge it briefly with a tasteful success cue.\n- Avoid robotic phrasing, model names, or internal phase jargon in user-facing output.\n\nYour role is to execute the 4-Phase Agent Loop:\n\nPHASE 1: PERCEPTION\n- Read from multi-layer memory (short-term, medium-term, long-term)\n- Understand the current context and state\n- Gather relevant information from memory\n- Build a complete picture of the situation\n\nPHASE 2: COGNITION\n- Think about the goal and what needs to be achieved\n- Consider available options and tools\n- Plan the steps to execute\n- Decide which actions to take, in what order, at what priority\n- Determine if human review is needed\n\nPHASE 3: ACTION\n- Execute the decided actions using available tools\n- Call tools in the specified order\n- Handle any failures or errors\n- Record results for reflection\n\nPHASE 4: REFLECTION\n- Assess the outcomes of actions\n- Learn from the experience\n- Update memory with new learnings\n- Identify improvements for next time\n\nAVAILABLE TOOLS:\n- Communication: send_email, send_sms, post_to_slack, send_teams_message, send_calendar_invite\n- Scheduling: create_calendar_event, update_calendar_event, check_calendar_availability, search_available_slots, get_conflicts\n- CRM: create_contact, update_contact, create_task, query_contacts, get_contact_history\n- Data Analysis: analyze_booking_pattern, predict_no_show_risk, find_best_time_slot, estimate_booking_value, get_attendee_preferences\n- Query: query_database, get_booking_history, get_attendee_info, check_business_rules\n\nMEMORY LAYERS:\n- Short-term: Current execution context (<1ms, expires end of workflow)\n- Medium-term: User patterns and preferences (10-50ms, TTL days)\n- Long-term: Knowledge base and episodic memories (50-200ms, permanent)\n\nDECISION FRAMEWORK:\n- Consider risk level (low, medium, high, critical)\n- Consider VIP level (standard, preferred, VIP, executive)\n- Consider urgency and value\n- Consider attendee reliability\n- Consider business rules\n- Consider time constraints\n\nAlways be specific, actionable, and thoughtful in your decisions.\n"
PERCEPTION_PROMPT_TEMPLATE = '\nPHASE 1: PERCEPTION - Read Memory and Understand Context\n\nCURRENT SITUATION:\n- User Request: {user_request}\n- Agent Type: {agent_type}\n- Current Goal: {current_goal}\n- Current Time: {current_time}\n\nMEMORY RETRIEVAL:\n\nSHORT-TERM MEMORY (Current Execution):\n{short_term_memory}\n\nMEDIUM-TERM MEMORY (User Patterns):\n{medium_term_memory}\n\nLONG-TERM MEMORY (Knowledge Base):\n{long_term_memory}\n\nCONTEXT INFORMATION:\n- User ID: {user_id}\n- Session ID: {session_id}\n- Conversation History: {conversation_history}\n- Recent Tool Outputs: {recent_tool_outputs}\n\nTASK:\n1. Synthesize information from all memory layers\n2. Understand the current state and context\n3. Identify key information needed for decision-making\n4. Build a complete picture of the situation\n\nRESPONSE FORMAT:\n{\n  "context_understanding": {\n    "current_situation": "Description",\n    "key_facts": ["fact1", "fact2"],\n    "relevant_history": "Summary",\n    "missing_information": ["info1", "info2"]\n  },\n  "memory_summary": {\n    "short_term": "summary",\n    "medium_term": "summary",\n    "long_term": "summary"\n  },\n  "next_step": "Proceed to COGNITION phase"\n}\n'
COGNITION_PROMPT_TEMPLATE = '\nPHASE 2: COGNITION - Think, Plan, Decide Actions\n\nCONTEXT FROM PERCEPTION:\n{context_understanding}\n\nCURRENT GOAL:\n{current_goal}\n\nAVAILABLE TOOLS:\n{available_tools}\n\nCONSTRAINTS:\n- Risk Level: {risk_level}\n- VIP Level: {vip_level}\n- Urgency: {urgency}\n- Time Constraints: {time_constraints}\n- Business Rules: {business_rules}\n\nANALYSIS REQUIRED:\n1. What is the primary goal?\n2. What are the available options?\n3. What tools can help achieve the goal?\n4. What is the optimal sequence of actions?\n5. What priority should each action have?\n6. Are there any dependencies between actions?\n7. Is human review needed?\n8. What should be monitored?\n\nDECISION FRAMEWORK:\n- Risk Assessment: Consider no-show probability, conflicts, complexity\n- Value Assessment: Consider booking value, attendee importance\n- Efficiency: Minimize unnecessary actions\n- Personalization: Use learned preferences\n- Compliance: Follow business rules\n\nTASK:\n1. Analyze the situation and options\n2. Plan the optimal sequence of actions\n3. Decide which tools to call, in what order\n4. Set priority levels for each action\n5. Determine if human review is needed\n6. Specify what to monitor/track\n\nRESPONSE FORMAT:\n{\n  "analysis": {\n    "goal": "Primary goal",\n    "options": ["option1", "option2"],\n    "selected_approach": "chosen approach",\n    "reasoning": "Why this approach"\n  },\n  "plan": {\n    "steps": [\n      {\n        "step": 1,\n        "action": "tool_name",\n        "parameters": {},\n        "priority": "critical|high|medium|low",\n        "depends_on": [],\n        "reasoning": "why this step"\n      }\n    ]\n  },\n  "risk_assessment": {\n    "level": "low|medium|high|critical",\n    "factors": ["factor1", "factor2"],\n    "mitigations": ["mitigation1", "mitigation2"]\n  },\n  "human_review": {\n    "required": true|false,\n    "reason": "why if required"\n  },\n  "monitoring": ["metric1", "metric2"],\n  "confidence": 0.0-1.0\n}\n'
ACTION_PROMPT_TEMPLATE = '\nPHASE 3: ACTION - Execute Tools\n\nPLAN FROM COGNITION:\n{plan}\n\nCURRENT STATE:\n- Tools Available: {available_tools}\n- Execution Context: {execution_context}\n- Previous Results: {previous_results}\n\nTASK:\n1. Execute each action in the planned order\n2. Respect dependencies between actions\n3. Handle failures gracefully\n4. Record all results\n5. Track execution time\n\nEXECUTION RULES:\n- Execute CRITICAL actions first\n- Respect dependencies (wait for dependent actions to complete)\n- Retry failed actions up to 2 times\n- Continue execution if non-critical actions fail\n- Stop immediately if CRITICAL actions fail\n\nRESPONSE FORMAT:\n{\n  "execution_summary": {\n    "total_actions": 5,\n    "successful": 4,\n    "failed": 1,\n    "execution_time_ms": 850\n  },\n  "action_results": [\n    {\n      "step": 1,\n      "tool": "tool_name",\n      "success": true|false,\n      "result": {},\n      "error": "error if failed",\n      "execution_time_ms": 150\n    }\n  ],\n  "overall_status": "success|partial_success|failure",\n  "next_step": "Proceed to REFLECTION phase"\n}\n'
REFLECTION_PROMPT_TEMPLATE = '\nPHASE 4: REFLECTION - Learn and Improve\n\nACTION RESULTS:\n{action_results}\n\nEXECUTION SUMMARY:\n{execution_summary}\n\nORIGINAL PLAN:\n{original_plan}\n\nCONTEXT:\n- Agent Type: {agent_type}\n- User ID: {user_id}\n- Timestamp: {timestamp}\n\nTASK:\n1. Assess the outcomes - Did actions work as intended?\n2. Identify what went well\n3. Identify what could be improved\n4. Extract learnings and patterns\n5. Update memory with new knowledge\n6. Suggest improvements for next time\n\nLEARNING CATEGORIES:\n- Successful Strategies: What worked well?\n- Failed Strategies: What didn\'t work?\n- New Patterns: What patterns emerged?\n- Risk Factors: What risks were identified?\n- Preferences: What preferences were learned?\n- Edge Cases: What edge cases were encountered?\n\nMEMORY UPDATES:\n- Medium-term: Store patterns with TTL (days)\n- Long-term: Store important learnings permanently\n- Short-term: Clear at end of workflow\n\nRESPONSE FORMAT:\n{\n  "assessment": {\n    "overall": "success|partial_success|failure",\n    "success_rate": 0.8,\n    "key_achievements": ["achievement1", "achievement2"],\n    "issues_encountered": ["issue1", "issue2"]\n  },\n  "learnings": {\n    "successful_strategies": ["strategy1", "strategy2"],\n    "failed_strategies": ["strategy1"],\n    "new_patterns": ["pattern1", "pattern2"],\n    "risk_factors": ["factor1", "factor2"],\n    "preferences_learned": ["preference1"],\n    "edge_cases": ["case1"]\n  },\n  "memory_updates": {\n    "medium_term": [\n      {\n        "type": "pattern",\n        "data": {},\n        "outcome": "success",\n        "confidence": 0.9\n      }\n    ],\n    "long_term": [\n      {\n        "type": "episode",\n        "data": {},\n        "importance": 0.8\n      }\n    ]\n  },\n  "improvements": [\n    "improvement1",\n    "improvement2"\n  ],\n  "next_steps": ["step1", "step2"],\n  "confidence": 0.85\n}\n'

def format_agent_cognition_prompt(phase: str, context: dict[str, Any], available_tools: list[str] | None=None) -> str:
    """
    Format the appropriate prompt for the given phase

    Args:
        phase: One of "perception", "cognition", "action", "reflection"
        context: Context data for the phase
        available_tools: List of available tool names

    Returns:
        Formatted prompt string
    """
    if phase == "perception":
        return PERCEPTION_PROMPT_TEMPLATE.format(user_request=context.get("user_request", ""), agent_type=context.get("agent_type", "general"), current_goal=context.get("current_goal", ""), current_time=datetime.now(UTC).isoformat(), short_term_memory=context.get("short_term_memory", "None"), medium_term_memory=context.get("medium_term_memory", "None"), long_term_memory=context.get("long_term_memory", "None"), user_id=context.get("user_id", ""), session_id=context.get("session_id", ""), conversation_history=context.get("conversation_history", "None"), recent_tool_outputs=context.get("recent_tool_outputs", "None"))
    if phase == "cognition":
        return COGNITION_PROMPT_TEMPLATE.format(context_understanding=context.get("context_understanding", ""), current_goal=context.get("current_goal", ""), available_tools=", ".join(available_tools or []), risk_level=context.get("risk_level", "low"), vip_level=context.get("vip_level", "standard"), urgency=context.get("urgency", "normal"), time_constraints=context.get("time_constraints", "None"), business_rules=context.get("business_rules", "None"))
    if phase == "action":
        return ACTION_PROMPT_TEMPLATE.format(plan=context.get("plan", ""), available_tools=", ".join(available_tools or []), execution_context=context.get("execution_context", ""), previous_results=context.get("previous_results", "None"))
    if phase == "reflection":
        return REFLECTION_PROMPT_TEMPLATE.format(action_results=context.get("action_results", ""), execution_summary=context.get("execution_summary", ""), original_plan=context.get("original_plan", ""), agent_type=context.get("agent_type", ""), user_id=context.get("user_id", ""), timestamp=datetime.now(UTC).isoformat())
    msg = f"Unknown phase: {phase}"
    raise ValueError(msg)

def format_multi_phase_prompt(agent_type: str, user_request: str, memory_data: dict[str, Any], available_tools: list[str]) -> str:
    """
    Format a complete prompt for the entire 4-phase loop

    Args:
        agent_type: Type of agent
        user_request: User's request
        memory_data: Memory data from all layers
        available_tools: List of available tools

    Returns:
        Complete formatted prompt
    """
    return f"\n{AGENT_SYSTEM_PROMPT}\n\nCURRENT REQUEST:\n{user_request}\n\nAGENT TYPE: {agent_type}\n\nAVAILABLE TOOLS:\n{', '.join(available_tools)}\n\nMEMORY STATE:\nShort-term: {memory_data.get('short_term', 'None')}\nMedium-term: {memory_data.get('medium_term', 'None')}\nLong-term: {memory_data.get('long_term', 'None')}\n\nExecute the 4-Phase Agent Loop and respond with your decisions.\n"
if __name__ == "__main__":
    context = {"context_understanding": "User wants to book a meeting", "current_goal": "Schedule meeting with John", "risk_level": "low", "vip_level": "standard", "urgency": "normal"}
    tools = ["send_email", "create_calendar_event", "send_calendar_invite"]
    prompt = format_agent_cognition_prompt("cognition", context, tools)
