export const googleOverlayStyles = {
  backdrop: "fixed inset-0 z-50 bg-[rgba(60,64,67,0.32)] backdrop-blur-[2px]",
  panel: "relative w-full overflow-hidden rounded-[28px] border border-[#DADCE0] bg-white shadow-[0_24px_60px_-36px_rgba(32,33,36,0.35)]",
  header: "flex items-center justify-between border-b border-[#DADCE0] px-6 py-4",
  body: "p-6",
  bodyScrollable: "max-h-[60vh] overflow-y-auto p-6",
  title: "text-base font-semibold text-[#202124]",
  subtitle: "text-sm text-[#5F6368]",
  label: "flex items-center gap-2 text-sm font-semibold text-[#202124]",
  field: "w-full rounded-xl border border-[#DADCE0] bg-white px-3 py-2.5 text-sm text-[#202124] outline-none transition-colors placeholder:text-[#80868B] focus:border-[#1A73E8] focus:ring-2 focus:ring-[#D2E3FC]",
  fieldMuted: "w-full rounded-xl border border-[#DADCE0] bg-[#F8F9FA] px-3 py-2.5 text-sm text-[#202124] outline-none transition-colors placeholder:text-[#80868B] focus:border-[#1A73E8] focus:bg-white focus:ring-2 focus:ring-[#D2E3FC]",
  section: "rounded-2xl border border-[#DADCE0] bg-[#F8F9FA] p-4",
  sectionTitle: "text-sm font-semibold text-[#202124]",
  helperText: "text-sm text-[#5F6368]",
  subtleText: "text-xs text-[#5F6368]",
  primaryButton: "inline-flex items-center justify-center rounded-xl bg-[#1A73E8] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#1558B0] disabled:cursor-not-allowed disabled:bg-[#D2E3FC] disabled:text-white/80",
  secondaryButton: "inline-flex items-center justify-center rounded-xl border border-[#DADCE0] bg-white px-4 py-2.5 text-sm font-semibold text-[#202124] transition hover:bg-[#F1F3F4] disabled:cursor-not-allowed disabled:opacity-70",
  ghostButton: "inline-flex items-center justify-center rounded-xl px-4 py-2.5 text-sm font-semibold text-[#202124] transition hover:bg-[#F1F3F4] disabled:cursor-not-allowed disabled:opacity-70",
  iconButton: "inline-flex items-center justify-center rounded-xl border border-[#DADCE0] bg-white text-[#5F6368] transition hover:bg-[#F1F3F4] hover:text-[#202124]",
  dangerButton: "inline-flex items-center justify-center rounded-xl border border-[#FDE7E9] bg-[#FDE7E9] text-[#D93025] transition hover:bg-[#FAD2D5] disabled:cursor-not-allowed disabled:opacity-70",
} as const;